name: 'SWE-Agent GitHub Action'
description: 'Automated software engineering agent for GitHub repositories'
author: 'Your Organization'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  webhook-secret:
    description: 'Secret for validating GitHub webhooks'
    required: true
  swe-agent-timeout:
    description: 'Timeout for SWE-Agent operations in milliseconds'
    required: false
    default: '300000'
  max-concurrent-jobs:
    description: 'Maximum number of concurrent SWE-Agent jobs'
    required: false
    default: '3'
  log-level:
    description: 'Logging level (error, warn, info, debug)'
    required: false
    default: 'info'

outputs:
  server-url:
    description: 'URL of the running webhook server'
    value: 'http://localhost:3000'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GITHUB_WEBHOOK_SECRET: ${{ inputs.webhook-secret }}
    SWE_AGENT_TIMEOUT: ${{ inputs.swe-agent-timeout }}
    MAX_CONCURRENT_JOBS: ${{ inputs.max-concurrent-jobs }}
    LOG_LEVEL: ${{ inputs.log-level }}

branding:
  icon: 'cpu'
  color: 'blue'