name: 'SWE-Agent Issue Resolver Action'
description: 'Triggers SWE-agent to attempt to fix a GitHub issue based on a comment.'
author: 'nimishchaudhari' # (nimishchaudhari - 2025-05-26)

inputs:
  github_token:
    description: 'GitHub token to interact with the repository (e.g., post comments, read issue data).'
    required: true
    default: ${{ github.token }}
  trigger_phrase:
    description: 'The phrase in comments to trigger the agent (e.g., "@swe-agent fix this"). The text after this phrase will be used as part of the problem description.'
    required: false
    default: '@swe-agent'
  llm_api_key:
    description: 'API key for the LLM used by SWE-agent (e.g., OpenAI API Key). Store as a repository secret.'
    required: true
  model_name:
    description: 'The model name to be used by SWE-agent (e.g., gpt-4-turbo, claude-3-opus-20240229).'
    required: false
    default: 'gpt-4-turbo' # A sensible default
  swe_agent_args:
    description: 'Optional additional arguments to pass directly to the SWE-agent run.py script.'
    required: false
    default: ''
  # Example: If SWE-agent needs a specific config file that can be part of your action or the target repo
  # swe_agent_config_file:
  #   description: 'Path to a specific SWE-agent configuration file (if needed beyond CLI args).'
  #   required: false
  #   default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  # Environment variables for entrypoint.sh are derived from inputs automatically:
  # INPUT_GITHUB_TOKEN, INPUT_TRIGGER_PHRASE, INPUT_LLM_API_KEY, INPUT_MODEL_NAME, INPUT_SWE_AGENT_ARGS

branding:
  icon: 'zap' # Changed icon
  color: 'green'