version: '3.8'

services:
  swe-agent-action:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SWE_AGENT_PATH=/usr/local/bin/swe-agent
      - SWE_AGENT_TIMEOUT=300000
      - LOG_LEVEL=info
      - MAX_CONCURRENT_JOBS=3
    volumes:
      - /tmp/swe-agent-jobs:/tmp/swe-agent-jobs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

networks:
  default:
    name: swe-agent-network