# Example workflow file to use in .github/workflows/swe-agent.yml
name: SWE-Agent Issue Resolver

on:
  issue_comment:
    types: [created]

jobs:
  generate-patch:
    if: github.event.issue.pull_request == null && contains(github.event.comment.body, '@swe-agent')
    runs-on: ubuntu-latest
    
    outputs:
      patch_generated: ${{ steps.swe-agent.outputs.patch_generated }}
      patch_content: ${{ steps.swe-agent.outputs.patch_content }}
      execution_time: ${{ steps.swe-agent.outputs.execution_time }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Run SWE-Agent
        id: swe-agent
        uses: your-username/swe-agent-resolver@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          llm_api_key: ${{ secrets.OPENAI_API_KEY }}
          model_name: 'gpt-4o'
          trigger_phrase: '@swe-agent'

  apply-patch:
    needs: generate-patch
    if: needs.generate-patch.outputs.patch_generated == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python (optional, for linting)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install linting tools (optional)
        run: |
          pip install black isort flake8 || true
      
      - name: Apply patch and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATCH_CONTENT: ${{ needs.generate-patch.outputs.patch_content }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          MODEL_NAME: 'gpt-4o'
          EXECUTION_TIME: ${{ needs.generate-patch.outputs.execution_time }}
        run: |
          set -e
          
          # Configure git
          git config --global user.name "swe-agent-bot"
          git config --global user.email "swe-agent-bot@users.noreply.github.com"
          
          # Create branch
          BRANCH_NAME="swe-agent-fix-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          
          # Apply patch
          echo "$PATCH_CONTENT" > /tmp/swe_agent_fix.patch
          
          if git apply --check /tmp/swe_agent_fix.patch; then
            git apply /tmp/swe_agent_fix.patch
            
            # Run linting/formatting if tools are available
            if command -v black >/dev/null 2>&1; then
              find . -name "*.py" -exec black {} + || true
            fi
            
            if command -v isort >/dev/null 2>&1; then
              find . -name "*.py" -exec isort {} + || true
            fi
            
            # Commit changes
            git add .
            git commit -m "Fix: Apply patch for issue #${ISSUE_NUMBER} by SWE-Agent

Issue: ${ISSUE_TITLE}
Model: ${MODEL_NAME}
Execution Time: ${EXECUTION_TIME}"
            
            # Push branch
            git push origin "$BRANCH_NAME"
            
            # Create PR using GitHub CLI
            PR_TITLE="SWE-Agent Fix for Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}"
            PR_BODY="This Pull Request was automatically generated by SWE-Agent.

**Issue:** #${ISSUE_NUMBER} - ${ISSUE_TITLE}
**Model:** ${MODEL_NAME}
**Execution Time:** ${EXECUTION_TIME}

## 🔧 Generated Patch
\`\`\`diff
${PATCH_CONTENT}
\`\`\`

## 📝 Next Steps
1. **Review** the changes in this PR
2. **Test** the changes locally if needed
3. **Merge** the PR if it resolves the issue

---
*✨ Generated by SWE-Agent using ${MODEL_NAME}*"
            
            # Get default branch
            DEFAULT_BRANCH=$(gh api repos/${{ github.repository }} --jq .default_branch)
            
            # Create PR
            PR_URL=$(gh pr create \
              --title "$PR_TITLE" \
              --body "$PR_BODY" \
              --base "$DEFAULT_BRANCH" \
              --head "$BRANCH_NAME")
            
            # Update the issue comment with success message
            COMMENT_ID="${{ github.event.comment.id }}"
            gh api repos/${{ github.repository }}/issues/comments/$COMMENT_ID \
              --method PATCH \
              --field body="✅ **Solution Generated & Pull Request Created!**

**Issue:** #${ISSUE_NUMBER} - ${ISSUE_TITLE}
**Model:** ${MODEL_NAME}
**Execution Time:** ${EXECUTION_TIME}
**Pull Request:** [View PR](${PR_URL})

## 🔧 Generated Patch
\`\`\`diff
${PATCH_CONTENT}
\`\`\`

## 📝 Next Steps
1. **Review** the Pull Request: [${PR_TITLE}](${PR_URL})
2. **Test** the changes in the PR
3. **Merge** the PR if it resolves the issue

---
*✨ Generated by SWE-Agent using ${MODEL_NAME}*"
          
          else
            echo "Patch could not be applied cleanly"
            
            # Update the issue comment with patch that couldn't be applied
            COMMENT_ID="${{ github.event.comment.id }}"
            gh api repos/${{ github.repository }}/issues/comments/$COMMENT_ID \
              --method PATCH \
              --field body="⚠️ **Patch Check Failed!**

**Issue:** #${ISSUE_NUMBER} - ${ISSUE_TITLE}
**Model:** ${MODEL_NAME}
**Execution Time:** ${EXECUTION_TIME}

The generated patch did not pass the \`git apply --check\` step. This indicates potential conflicts or issues with the patch.

## 🔧 Generated Patch (Problematic)
\`\`\`diff
${PATCH_CONTENT}
\`\`\`

Please review the patch and apply it manually if needed.

---
*⚠️ Analysis by SWE-Agent using ${MODEL_NAME}*"
            
            exit 1
          fi
