tools:
  submit:
    signature: "submit [<target_file>]"
    docstring: "submits the current file"
    arguments:
      - name: target_file
        type: string
        description: "the file to submit (if not provided, submits the diff)"
        required: false

