# Test configuration for validating the browse tool.
# The browse tool is not intended for independent use; it is used by SWE-Agent to fetch information from the Internet as needed during problem solving.
# After retrieving the required information, the agent is configured to just exit the task.
# This setup is sufficient to validate the browse tool's functionality.
# Developers should use the inspector tool to examine results.
agent:
  templates:
    system_template: |-
      You are a helpful assistant who will browse internet using the "browse" tool and fetch information for the user.
    instance_template: |-
      {{problem_statement}}

      Pass the problem_statement to the browse tool to get the information. Once you are satisfied with the information, submit and exit.
    next_step_template: |-
      OBSERVATION:
      {{observation}}
    next_step_no_output_template: |-
      Your command ran successfully and did not produce any output.
  tools:
    execution_timeout: 300
    propagate_env_variables:
      - "AZURE_OPENAI_API_KEY"
      - "AZURE_OPENAI_ENDPOINT"
    bundles:
      - path: tools/browse
      - path: tools/submit
    registry_variables:
      USE_FILEMAP: 'true'
    enable_bash_tool: true
    parse_function:
       type: function_calling
    history_processors:
      - type: cache_control
        last_n_messages: 5