name: SWE-Agent Enhanced Features Demo

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode to run'
        required: true
        default: 'integration'
        type: choice
        options:
          - 'integration'
          - 'opinion'
          - 'analysis'
          - 'visual'

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  # Demo job showing enhanced features in action
  demo-enhanced-features:
    if: contains(github.event.comment.body, '@swe-agent-demo') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Enhanced SWE-Agent (Opinion Mode)
        if: contains(github.event.comment.body, 'opinion') || github.event.inputs.test_mode == 'opinion'
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          model_name: 'gpt-4o'
          response_mode: 'opinion'
          enable_visual_content: 'true'
          
      - name: Run Enhanced SWE-Agent (Analysis Mode)
        if: contains(github.event.comment.body, 'analysis') || github.event.inputs.test_mode == 'analysis'
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          model_name: 'gpt-4o'
          response_mode: 'analysis'
          enable_visual_content: 'true'
          
      - name: Run Enhanced SWE-Agent (Auto Mode)
        if: github.event.inputs.test_mode == 'integration' || (!contains(github.event.comment.body, 'opinion') && !contains(github.event.comment.body, 'analysis'))
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          model_name: 'gpt-4o'
          response_mode: 'auto'
          enable_visual_content: 'true'
          visual_content_format: 'all'
          max_comment_length: '32768'
