name: SWE Agent

on:
  issue_comment:            { types: [created] }
  pull_request_review_comment: { types: [created] }
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [ main ]      # to scan commit messages

jobs:
  swe_agent:
    if: |
      (github.event_name == 'issue_comment' &&
       contains(github.event.comment.body, '@swe-agent')) ||
      (github.event_name == 'pull_request_review_comment' &&
       contains(github.event.comment.body, '@swe-agent')) ||
      (github.event_name == 'pull_request_target' &&
       contains(github.event.pull_request.body || '', '@swe-agent')) ||
      (github.event_name == 'push' &&
       contains(github.event.head_commit.message, '@swe-agent'))
    runs-on: ubuntu-latest

    permissions:            # least-privilege for autonomous code pushes
      contents: write
      pull-requests: write
      issues: write

    env:
      TRIGGER_PHRASE: "@swe-agent"
      OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
      # or ANTHROPIC_API_KEY / MISTRAL_API_KEY …
      SWE_AGENT_MODEL: "gpt-4o-mini"          # example override
      GITHUB_TOKEN:    ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install SWE-agent
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/SWE-agent/SWE-agent

      - name: Run SWE-agent wrapper
        run: python .github/actions/swe_agent_entrypoint.py
