name: SWE-Agent Issue Resolver

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  resolve_issue:
    name: Resolve Issue with SWE-Agent
    runs-on: ubuntu-latest
    if: |
      github.event.comment.user.login != 'github-actions[bot]' &&
      contains(github.event.comment.body, '@swe-agent') &&
      (github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment')
    
    steps:
      - name: Check if commenter has permissions
        id: check_permissions
        uses: actions/github-script@v7
        with:
          script: |
            const { data: collaborators } = await github.rest.repos.listCollaborators({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            const hasPermission = collaborators.some(collaborator => 
              collaborator.login === context.payload.comment.user.login
            );
            
            if (!hasPermission) {
              await github.rest.issues.createComment({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Sorry @${context.payload.comment.user.login}, only repository collaborators can trigger SWE-Agent.`
              });
            }
            
            return hasPermission;

      - name: Run SWE-Agent Resolver
        if: steps.check_permissions.outputs.result == 'true'
        uses: nimishchaudhari/SWE-agent-resolver@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          llm_api_key: ${{ secrets.OPENAI_API_KEY }}
          model_name: ${{ vars.SWE_AGENT_MODEL || 'gpt-4o' }}
          timeout_minutes: 30
          max_patch_size: 50000